// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aysconsultores.dotnet_web_api.Helpers;

#nullable disable

namespace aysconsultores.dotnet_web_api.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    [Migration("20220518010521_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aysconsultores.dotnet_web_api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "fernando.calmet@aysconsultores.pe",
                            FirstName = "Fernando",
                            Gender = (byte)1,
                            LastName = "Calmet",
                            Password = "12345678",
                            Username = "fcalmet"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.injante@aysconsultores.pe",
                            FirstName = "Maria",
                            Gender = (byte)2,
                            LastName = "Injante",
                            Password = "12345678",
                            Username = "minjante"
                        },
                        new
                        {
                            Id = 3,
                            Email = "carlos.perez@aysconsultores.pe",
                            FirstName = "Carlos",
                            Gender = (byte)1,
                            LastName = "Perez",
                            Password = "12345678",
                            Username = "cperez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
